# Generated by Django 5.2.6 on 2026-01-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='promo_codes', to='films.film'),
        ),
    ]
